### ISSUE TITLE
Improve the help note of the default .env file

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#102]
In https://github.com/symfony/recipes/blob/master/symfony/flex/1.0/.env.dist you can read:

> This file is a "template" of which env vars needs to be defined in your configuration or in an .env file
> Set variables here that may be different on each deployment target of the app, e.g. development, staging, production.

But we are usually told that .env and DotEnv component are only for development. So we should reword that help note. Thanks!

**Comment by BoShurik** [comment]
I prefer using DotEnv in production or using old `parameters.yml` system because setting environment variables for all use cases are not easy:
- Set variables for nginx/php-fpm
- Set variables for cli

And when I try to deploy app with `Capistrano` this variables are undefined because terminal is non-interactive and doesn't load `.bash_profile`

**Comment by stof** [comment]
@BoShurik you can put them in `.bashrc` rather than `.bash_profile` :)

**Comment by fabpot** [comment]
see #174
