### ISSUE TITLE
[RFC] Rename translation.yaml to translator.yaml

### ISSUE THREAD

**Issue by yceruto** [symfony/recipes#252]
https://github.com/symfony/recipes/blob/db32040b48e9cf15299e7702a75a49e76999ff3f/symfony/translation/3.3/config/packages/translation.yaml#L1-L3

Shouldn't the configuration filename have the same name as the alias key configuration? Inconsistent with the rest of the cases.

**Comment by Pierstoval** [comment]
It's for the `symfony/translation` component, so for me, `translation` is ok :thinking:

**Comment by yceruto** [comment]
@Pierstoval I'm not sure about that, in some place I read that it should match with the config key, but I don't remember where :(

Btw, I think it's not mandatory because `symfony/framework-bundle` and `framework.yaml` does not match in that sense.

**Comment by Pierstoval** [comment]
Framework & translation are different, indeed it should match the config key, but `symfony/translation` is not a config it's a symfony component which can be configured by the FrameworkBundle.

The problem here is that everything is handled from the FrameworkBundle...

So indeed this question can be asked, whether to use `translation` or `translator`, but I personally tend to think the "global" way, by saying that it's about the Translation component, and not only the "translator". Because you also have the translation commands, locales, etc.

**Comment by chalasr** [comment]
IMHO the package should have been called `translator`, it's inconsistent with others e.g. `serializer` and `validator`.
But here we are and, given the directory is called `packages`, I expect to find files named exactly as the package they relate to, so I'm -1 for using a different name.

**Comment by yceruto** [comment]
Agree, fair enough :)
