### ISSUE TITLE
Missing in readme how to add a repository

### ISSUE THREAD

**Issue by iltar** [symfony/recipes#29]
In Fabien's blog this is stated:

> The "main" official repository, hosted at https://github.com/symfony/recipes will be opinionated. Submissions will be reviewed carefully. They will need approval from the Symfony core team (like pull requests on the main symfony/symfony repository). We want the utmost quality and the best developer experience.

But I could not find out what the requirements would be for such an addition. Lets say I would like to add a bundle, what would my PR need besides of that which you add in the contrib repository? 
 - Would it have to include research on other (similar) bundles with pros and cons? 
 - Would there be a quality requirement? 
 - Stability requirement?
 - PSR Requirement?
 - What about testing requirements?
 - CI?

I know it's kinda fuzzy to define all those, but it would be nice to have an indication.

**Comment by Pierstoval** [comment]
Flex isn't released yet, so be patient and wait until all blog posts come up 😉 

I'm sure you'll get your answers very soon!

**Comment by iltar** [comment]
Regardless of blog posts, this is info I'd expect to find inside the repository

**Comment by Pierstoval** [comment]
I guess that recipes will be reviewed by Symfony core developers, _and_ contributors, and actually, I don't like the idea of having recipes to be posted on either this repo or [symfony/recipes-contrib](https://github.com/symfony/recipes-contrib) _before_ flex is out, because it wouldn't be testable then 😃 

Still, I'm sure we just have to wait for this and that all needed work is in progress 🙂

**Comment by Pierstoval** [comment]
Plus, I think using Github's default templates for issues & pull-requests is a good starter for this kind of requirements! Like the one we have for Symfony, actually

**Comment by iltar** [comment]
I think that would actually be a great addition for this!

**Comment by javiereguiluz** [comment]
A possible inspiration may be the [Magento Extensions Quality Program](https://magento.com/blog/technical/improvements-magento%E2%80%99s-extension-quality-program) which combines manual and automatic checks/reviews for the business, marketing an tech part of the extension.

**Comment by Pierstoval** [comment]
Requiring code coverage & SLInsight platinum badge & php-cs-fixer rules for example could be a good start too 😃

**Comment by iltar** [comment]
I think it would be really cool to provide tools to increase the quality of your open-source package as "recommended" by Symfony anyway. Including guides on how to do so. Travis is a really powerful tool and there dozens of tools that can be used here.

For this repository, it can be a requirement. For the contrib repository, it could be a recommendation.

**Comment by sstok** [comment]
Code coverage is a tricky one, 100% coverage doesn't guarantee that code is free from bugs. As such as 70% can still mean very good but hard to test parts, because it's all infrastructure related.

I think for the main repository we shouldn't allow packages that have existed for less 3 (6?) months and have at least some stable user base and download count (say 30 or so). Let them start in the contrib and work there way-up to the main one 👍

**Comment by Pierstoval** [comment]
@sstok This is obvious that code coverage doesn't guarantee anything. Nor does SLInsight or php-cs-fixer (they can be "hacked" with special configuration). But still it's a first step before allowing the recipe to be checked by the team :)

**Comment by fabpot** [comment]
Closing this old thread. I think acceptance in the official repo is indeed fuzzy, and writing strict rules would not make sense IMHO.
