### ISSUE TITLE
[RFC] Demo recipes

### ISSUE THREAD

**Issue by renatomefi** [symfony/recipes#309]
Hello,

I see many symfony bundles providing demo applications to help the users with their best practices and/or how to actually expand their application using the bundle features.

Some problems related:
- Those repositories get outdated, symfony and bundle wise
- It requires the user to clone a project and not experience how it is to setup the application

Advantages:
- The demos following the recipe will make it clear what is being copied
- It can be removed
- You can maintain easily the versions update
- Makes symfony flex even more used

Proposed solutions: (Choose one to discuss)
- [ ] Make a "install demo [y/N]" during the require process
- [ ] A new recipes-demo repository
- [ ] Allow current recipes to install the demo either way (least favorite for me)
- [ ] Something else? Comments please

I'm looking forward to hear some opinions on this

**Comment by Pierstoval** [comment]
A demonstration is just a simple project, I don't find clear value in adding a "demo" feature to recipes.

Instead, one could simply provide another skeleton-like application, like Symfony, and then add their own composer package and recipe that would copy files from the package instead of the recipe, so they don't have to update the recipe everytime and can just update their package instead, so it becomes easier for them to maintain their demo application in the package themselves instead of a specific package/recipe.

Not sure I'm clear enough, so TL;DR:

* Create a "skeleton" project, like `symfony/skeleton` but with your project
* Create a special pack on packagist.org with a custom repo of yours, simplest one
* Create a recipe that `copy-from-package` some config files that would come from the previously created pack's repository (demo configuration, just to say)
* Tell people to install the demo by just running `composer create my-vendor/my-demo-skeleton` and that's it.

But I bet @fabpot's next announcements about Flex might be really helpful for you, because he will provide new features to Flex & packages that would allow you to implement such demo applications in a nutshell 😉
