### ISSUE TITLE
Multiple configurations recipes

### ISSUE THREAD

**Issue by tattali** [symfony/recipes#360]
Hello, 
is there a way to add an argument to the bundle installation command?

For example : FOSUserBundle is mostly used with Doctrine orm, but we can also use MongoDB or CouchDB.

https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#a-doctrine-orm-user-class

Maybe with an argument like `--orm="doctrine"`. 
Recipes with the three configurations could be added.

Thanks

**Comment by Pierstoval** [comment]
There's no additionnal command and I don't think it's going to change, because flex is not made for this.

If you need the ODM, then it just means you won't use the default config, so you can use `composer req ... --no-scripts` to disable the post-install scripts, update your config to use the ODM, and then run `composer run auto-scripts` to run the scripts manually.

**Comment by weaverryan** [comment]
One option is to create a meta/package that itself requires FOSUserBundle, and attach the recipe to that meta package :)

**Comment by Nyholm** [comment]
Thank you for your answers.
