### ISSUE TITLE
[DX Proposal] Put the `App` classes in a `App` directory.

### ISSUE THREAD

**Issue by frankdejonge** [symfony/recipes#407]
Currently the default autoloading and placement of the base minimum installation makes relates the `src/` folder to the `App` namespace. When you want to create an additional top-level namespace (for your business' domain) things start to get a little tricky. Do you place it in `src/Acme/`? In which case the src folder serves as the root for 2 namespaces. Do you create a new src-like folder for your code? Now the `src` folder makes less sense because the source is now split across two folders. Or do you move all the "framework" stuff into an `App` folder? In that case you'll have to adjust the autoloading config and all the recipes will place their core in the old location and you'll be forces to move it, not ideal.

My suggestion would be to place all the framework related stuff in the `src/App` folder from the start. I realise this may have been a discussion point during the 4.0 planning and that changing this after the release is somewhat problematic. However I feel like this could really improve the experience when starting out with Symfony for people who are used to splitting framework and domain specific code.

**Comment by frankdejonge** [comment]
Btw, if this issue should be moved to the main symfony repository, let me know and I'll close this and re-open there.

**Comment by weaverryan** [comment]
There are a lot of good arguments for this, but the fact that this would be such a big change, really makes it a hard sell. Also, for devs who don’t split things into multiple namespaces (like, I don’t), it introduces a dead directory - the src/ dir now only holds App/. We wanted to move away from that - extra depth adds perceived complexity.

So I would be a maybe on this pre 4.0. But as you mentioned, post 4.0, it’s problematic.

The compromise might just be to doc how to make this change. Other than moving a lot of files, adding this dxtta directory later is a super safe operation, because you only need to adjust autoloading.

**Comment by Pierstoval** [comment]
Having `src/App` means that anyone creating other namespaces will still have to deal with the differences between `src/App` and their own namespaces when Flex will install some recipes that store code in this namespace, or when they'll use the maker which is based on this. It's like having the AppBundle + other bundles. 

Same as Ryan: for 4.x it'll probably be difficult to move all recipes to a new syntax. Maybe options could be given to Flex to customize this behavior, but it has been asked a lot and never implemented yet, probably because of the original recommendations of the Symfony team about how to organize an app with Flex 🤔.

I'm not sure what kind of solution could really be found 😕

**Comment by fabpot** [comment]
"My suggestion would be to place all the framework related stuff in the src/App folder from the start." The `src` directory is all about **your** code, there is no "framework related stuff" anywhere. You could argue that the controllers are part of the framework, but this is really your own code, tied to Symfony in a way if you want.

Anyway, I think documenting how to add the `App/` directory and updating the autoloading for people willing to have more than one root namespace seems like the best thing to do IMHO.
