### ISSUE TITLE
Do we really need a phpunit.xml.dist file?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#41]
In the PHPUnitBridge recipe, we have this file: https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/3.3/phpunit.xml.dist

I know the theory behind it: we give you a `phpunit.xml.dist` so you commit it to the repo and then you create a `phpunit.xml` with your own changes.

Now, my question: is this scenario really that common? In real projects with several developers, do each of them create their own and different phpunit.xml file ... or do they all use the same PHPUnit config file? Should we remote the `phpunit.xml.dist` file and only use `phpunit.xml`?

**Comment by stof** [comment]
the difference is that PHPUnit will load the `phpunit.xml.dist` file if `phpunit.xml` does not exist. So you don't need to copy it unless you want to do special stuff.
So committing a `phpunit.xml.dist` in the repo (and adding `phpunit.xml` in the gitignore) is just about following the PHPUnit best practice

**Comment by javiereguiluz** [comment]
Even if it's a "best practice", I wonder if it's still needed.

For example, until recently we said that creating bundles was a "best practice" and not using umask() was a "best practice" ... but the next Symfony version removes bundles and uses umask by default to avoid permission issues. So maybe we can rethink this "best practice" too if it no longer makes sense.

Personally I don't know if it makes sense. My guess is that everybody working on the same project needs the exact same PHPUnit config file. But 'd like to know if that's true or not.

**Comment by Pierstoval** [comment]
I think it's still useful to propose a dist file for PHPUnit. In dev, when you have a very big test suite, you sometimes need to execute as maller part, or to change some environment vars to limit the tests to execute, or to lighten the test suite without being forced to name the class and the method, if you want an isolated test because it takes lot of time. Or if you need to customize tests bootstraping process.

It's PHPUnit's best practices, so I would recommend to keep it. I personally use this feature, could it be for my private or open-source projects 🙂

**Comment by fabpot** [comment]
I'm not sure I understand the reasoning behind changing that. The fact that the name is `.xml.dist` or `.xml` does not change anything. You don't need to create a `phpunit.xml` file. I never do that and it just works. So, keeping it like this means more flexibility if you need it, but it does not make the experience any different for people not using it.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix". Thanks!
