### ISSUE TITLE
Recipe execution order bug

### ISSUE THREAD

**Issue by webmake** [symfony/recipes#414]
![image](https://user-images.githubusercontent.com/5016464/40782119-01a0ebbe-64e7-11e8-8a54-98628b7494ca.png)

missing phpunit recipe

Steps to reproduce:

Left side (OK):
```
$ composer create-project symfony/skeleton blog
$ cd blog
$ composer req phpunit/phpunit
$ composer req doctrine/doctrine-bundle doctrine/doctrine-migrations-bundle doctrine/orm
```
Right side (in different order missing phpunit xml):
```
$ composer create-project symfony/skeleton blog2
$ cd blog2
$ composer req doctrine/doctrine-bundle doctrine/doctrine-migrations-bundle doctrine/orm
$ composer req phpunit/phpunit
```

**Comment by fabpot** [comment]
This is the expected behavior... even if this is not what you'd expect :) A recipe is applied in the context of what you have at that point. So, in the second example, when installing Doctrine bundle, there is no phpunit.xml.dist file, so it's not updated. Now, when installing phpunit, there is no (easy) way to check that anything that was installed before would not trigger some modification to the new file.

So, as I don't see any easy fix, I'm going to close as a won't fix.

Thanks for reporting.

**Comment by webmake** [comment]
I suspect this could affect only env files? What if modifying env attributes would inform at least, that not all recices could be executed, so that user would compare .env with phpunit.xml?
