### ISSUE TITLE
Doctrine Bundle assumes the ORM is installed and adds config for it

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/recipes#428]
See https://github.com/doctrine/DoctrineMigrationsBundle/issues/232

Essentially, unless the ORM is installed, an error is thrown preventing the console command to fire. The solution is to remove the ORM config added by the recipe.

**Comment by kejwmen** [comment]
I will reply to a comment from original issue.

> Nothing should be 'assumed' though! That's the issue! Symfony is a lot of components that are separate and independent, not some components that are assumed to be used together with others.

Yes, and recipes don't change it. 
Doctrine bundle integrates both orm and dbal, and I guess that almost everyone uses it with orm. So it makes more sense to make configuration easier for "almost everyone" by supporting the most common workflow.

And they are especially useful for newcomers. When you make conscious decision to use only DBAL and it's symfony integration, this is a custom workflow.

Imagine that recipe is changed to support dbal-only workflow out of the box. Then configuration is not automated anymore, because other developers (most of them) need to enable orm manually.

Recipe is a template, and at some point you'll change bundle configuration anyway to enable feature that is disabled by default or to replace default behavior with something better for your needs.

If you don't know how bundle is configured, recipe should make it work if all basic deps are installed. So you can start working with it and learn.

**Comment by ChangePlaces** [comment]
> And they are especially useful for newcomers. When you make conscious decision to use only DBAL and it's symfony integration, this is a __custom workflow__.

So, are you suggesting that you MUST use ORM with Symfony, and stating that Symfony is not a series of separate components?

I'm not advocating the recipe be changed to support DBAL only, I'm stating it should detect whether the ORM is installed. If it is, add the config, if it isn't don't. If it's insisted on adding the config, make the ORM a dependency of the migrations bundle.

> recipe should make it work if all basic deps are installed.

I agree, the ORM is not a dependency. Surprisingly only DBAL is, which is ironically broken by the install.

**Comment by Nyholm** [comment]
Thank you. This is an interesting issue. What you basically did is that you installed `doctrine/doctrine-bundle`. That recipe adds configuration for ORM but the ORM package was never pulled. (Since `doctrine/orm` is not a dependency of `doctrine/doctrine-bundle`. 

As @kejwmen suggests, recipes are templates for configuration that are good for 95% of the users. In this scenario (which is super valid) you are a part of those 5%. 

--------

One solution could be to move the doctrine bundle config (or parts of it) to the symfony/orm-pack. But Im not sure that is a route we want to take. 

--------

I recognize this issue and suggest to close it as "wont-fix".

**Comment by Pierstoval** [comment]
> One solution could be to move the doctrine bundle config (or parts of it) to the symfony/orm-pack. But Im not sure that is a route we want to take.

Or we can split the DoctrineBundle's configuration, one for the doctrine/dbal package and the other one for doctrine/orm?

We're quite unlikely to require any of these two without requiring the DoctrineBundle anyway

**Comment by Nyholm** [comment]
I thought about that as well.

> We're quite unlikely to require any of these two without requiring the DoctrineBundle anyway

Yes, as unlikely as the current situation. =)

But to install "symfony bundle configuration" when requiring a library feels wrong 😕

**Comment by Pierstoval** [comment]
Yep, it's just that Flex is mostly compatible with Symfony-based applications. If you're actually using Flex without requiring the skeleton, this becomes the "marginal case", and I consider _this_ marginal case to be the one where you delete spare config you don't use, and the other one, more frequent, where you require the skeleton and then add the bundle & dbal without orm for example, where you should retrieve the dbal config but not the ORM one.

Not sure I'm clear enough 😅

**Comment by ChangePlaces** [comment]
I see the general consensus is essentially, "given the current framework, this is too difficult to solve". I wasted at least an hour figuring out what was the cause - at least put something in the docs about it.

Just because it's popular is not the reason to include extra config "just in case" the user decides to install the ORM.

**Comment by kejwmen** [comment]
> Stuff broke with zero feedback as to why.

I have two ideas:

Maybe doctrine bundle docs can point out that in case of DBAL-only setup recipe must be changed (and how).

Exception is thrown inside bundle, maybe we can add some context to error message to improve DX?

Of course this is not related to recipe, we can create an issue in bundle repo.

And going back to:

> So, are you suggesting that you MUST use ORM with Symfony, and stating that Symfony is not a series of separate components?

No, my main point is about improving DX for new developers. Considering current flex implementation (which is an optional tool that makes configuration easier, but not always optional) this is the best option we have.
This bundle is a specific case (usually bundle integrates a specific lib), here it makes more sense to autoconfigure it for almost all developers (and this is why devs love flex) than to break ORM autoconfiguration because it can be used without ORM.

And the only thing we can do is to improve docs or error messages - I've seen a lot of improvements in this matter in the last months, this is just another place where it's worth to do this.

**Comment by XWB** [comment]
> I'm stating it should detect whether the ORM is installed

I'm not sure if that's possible. As pointed out earlier by @fabpot in https://github.com/symfony/flex/issues/344#issuecomment-377873799, Symfony Flex is not interactive so there is no way of knowing whether the user wants to use the ORM or not.

Recipes are all about default configuration, but you can always remove the ORM integration afterwards.

**Comment by iquito** [comment]
I am also a user of only DBAL, not the ORM, and I think the number of users only using DBAL is underestimated. DBAL integration is so easy with Symfony, which is why I think a vast majority of Symfony projects use DBAL, but quite a few don't use the ORM - they use DBAL as an improved version of PDO, or as the basis to build an own DB access class. DBAL has so many valid use cases on its own.

Having two bundles (like doctrine-dbal-bundle and doctrine-orm-bundle) would be very advantageous for easy usage, and the naming would be clear too. Then doctrine-orm-bundle can build on doctrine-dbal-bundle, and doctrine-doctrine-bundle can be an alias of doctrine-orm-bundle (or doctrine-doctrine-bundle would just be the orm bundle).

**Comment by cawolf** [comment]
I stumbled upon this recipe when developing a DBAL focused bundle.

> If this bundle adds config for the ORM, it should have a dependency for the ORM.

Like @ChangePlaces wrote, this is the essence. I don't quite get why this rule is broken on purpose in this case. My assumption is, that it will be a lot of work (documentation-wise).

> Having two bundles (like doctrine/dbal-bundle and doctrine/orm-bundle) would be very advantageous for easy usage, and the naming would be clear too.

I second @iquito 's proprosal. If anybody who is not affiliated with Symfony would contribute a recipe for a bundle, and install configuration files for another bundle, which was not a dependency, I'm not sure if the PR would be merged to the flex recipe repository at all.

**Comment by jkufner** [comment]
I think the best solution is to split the configuration into two files — one for DBAL and another for ORM. Then create a new recipe, that will install only the DBAL part. This way there is no BC break and DBAL-only users will be happy (including me).

If I understand the recipes correctly, we can use symlinks between the two recipes to share DBAL config.

Additional improvement would be to split the Doctrine bundle as well. It shoud be quite simple because it already works fine without the ORM component. The split would clear up the dependencies and would allow a hard dependency on ORM.

**Comment by derrabus** [comment]
> Additional improvement would be to split the Doctrine bundle as well.

➡️ doctrine/DoctrineBundle#973

**Comment by nicolas-grekas** [comment]
Closing as this requires work to happen before, see previous comment.
