### ISSUE TITLE
New asset.yaml in webpack-encore-pack file has broke project install

### ISSUE THREAD

**Issue by dspiegel** [symfony/recipes#438]
I'm not sure how, but today a new asset.yaml file showed up in packages folder when doing project create. My project uses asset versions, but new asset.yaml file defines asset json_manitfest_path. json_manifest_path conflicts with version definition and cause project install to fail.

```
!!    Invalid configuration for path "framework.assets": You cannot use both "ver  
!!    sion" and "json_manifest_path" at the same time under "assets".              
```
Another issue that started yesterday was yarn no longer installs encore.

Get error:
`An unexpected error occurred: "Reduce of empty array with no initial value"
`

Project install worked flawlessly up to and including Friday July 13th 2018, but now without any changes to my project, wepack-encore appears to have broke something.

I will have to modify my project to override new assets.yaml file, but the other issue I  am unsure of cause or hoe to fix. 

I don't agree with webpack-encore adding defaults settings to a flex recipe for a different library (framework). I believe those changes should reside as part of parent library, in this case symfony/framework.

Thanks, Dave

**Comment by Pierstoval** [comment]
> I don't agree with webpack-encore adding defaults settings to a flex recipe for a different library (framework). I believe those changes should reside as part of parent library, in this case symfony/framework.

This is probably not possible because the framework is the entry point to enable lots of features of the whole framework. There is no point of adding configuration for all 30 components to a single file like this, especially when config is commented and never used.
Splitting the framework's config in multiple files like this is the best option to decouple all packages config.

For your issue, did you version your `symfony.lock` file? If not, maybe that's why reinstalling the project re-applied the recipe.

If not, then this is just the basics of new projects with Flex: default config adapts to current and common usages and also best practices 😄 And good practices of versioning for assets is to use Webpack's feature to create hashes in built assets & add them to a JSON manifest file, and luckily we can load this manifest file when using the Asset component from Symfony to get the right url when using `{{ asset('...') }}}` in our views 👍
