### ISSUE TITLE
--env no longer equivalent to APP_ENV

### ISSUE THREAD

**Issue by bendavies** [symfony/recipes#497]
Related to https://github.com/symfony/recipes/pull/491

These two should be equivalent, shouldn't they?

```bash
> APP_ENV=prod APP_DEBUG=0 bin/console cache:clear --no-warmup
> bin/console cache:clear --no-warmup --env=prod --no-debug
```

Reproducer:

```bash
> composer create-project symfony/skeleton skeleton 
> cd skeleton
> rm -rf vendor
> composer install --no-dev #error will be here too.
> bin/console cache:clear --no-warmup --env=prod --no-debug

> Fatal error: Uncaught RuntimeException: The "APP_ENV" environment variable is not set to "prod". Please run "composer require symfony/dotenv" to load the ".env" files configuring the application. in project/src/.bootstrap.php on line 13
```

Thanks

**Comment by nicolas-grekas** [comment]
We did that on purpose: defining the real APP_ENV to prod means opting out from loading .env files.
--env prod loads .env file. The fatal error is bad though :) We should replace it with a better behavior, and also merge https://github.com/symfony/skeleton/pull/122 IMHO (and you can move Dotenv to "require" meanwhile).
ping @weaverryan FYI, WDYT?

**Comment by bendavies** [comment]
right, so --env and --no-debug are **not** equivalent to APP_ENV and APP_DEBUG any more?
That's a pretty big gotcha.

**Comment by nicolas-grekas** [comment]
Hum, the exception is right, you should require dotenv.
We should move it by default to "require" to me, please support https://github.com/symfony/recipes/issues/497 if you agree.

**Comment by bendavies** [comment]
I'm afraid I can't agree since (repeating myself - sorry), it seems really poor from a DX perspective that `--env` and `APP_ENV` are not equivalent, as @Tobion pointed out.

It seems like breaking change to me. what is the BC policy here?

FYI, we had mostly migrated an app to completely use env vars, but had some older supervisord jobs using `--env=prod`, and they broke as soon as this change was deployed.

**Comment by nicolas-grekas** [comment]
I understand the current behavior might not be unanimously OK, but the BC break argument makes no sense to me: you don't apply new recipes on existing code automatically. It's your responsibility to commit the resulting file and once done, they won't change unless you accept the change.

**Comment by bendavies** [comment]
I get what you are saying about BC, but from my point of view:

the app started on symfony 4.1, I updated a recipe [as suggested](https://symfony.com/doc/current/configuration/dot-env-changes.html) (because i'm a good boy!), the app is still on symfony 4.1, and the result is  an error in production which would have been very hard, almost impossible, for us to catch in tests.

I hope I'm making my point clear!
Thanks for considering!

**Comment by weaverryan** [comment]
>  would expect no functional changes at all, apart from those obvious ones documented.

Then it might be best fixed in documentation. Seen from the opposite perspective, suppose a project is *not* using real env vars - they have a `.env.local` on production. They run `bin/console cache:clear --env=prod` (or maybe `--env=dev` for some reason) and suddenly their `.env` files are not loaded. The env vars ARE loaded without the flag, however.

The new logic is meant to be simple: if you use real ENV vars (specifically `APP_ENV=prod`), the `.env` files are not loaded. If you do NOT use real env vars, the `.env` files *are* loaded.

Let me know if that makes sense!

**Comment by bendavies** [comment]
hi @weaverryan, thanks for the reply.

I understand what you are saying - it makes sense - but I can't agree as stated above :)

I don't see how a such large change in behaviour can be brought in seemingly under the radar. 
Obviously this should be documented if it's going to remain, but i'd question how many will notice and how many people will be caught out, despite documented.

Apologies for kicking up such a fuss, I just don't like being caught out in production :)

Cheers

**Comment by weaverryan** [comment]
@bendavies No worries :). Actually, I could use your help. I was just checking into adding some notes about this. But, I'm confused about what the functionality was BEFORE. Here's the `bin/console` file back from before the recent changes: https://github.com/symfony/recipes/blob/584967704025c23f12165a259fd80a5ad7717509/symfony/console/3.3/bin/console

Based on your comments, I was *expecting* that, when `--env=prod` was passed, the `.env` file was not loaded. But the code there looks like `.env` IS loaded with `--env=prod` (unless you also have a real `APP_ENV=prod` env var set).

I'm certain I'm misunderstanding a subtle thing here... and so, almost certainly something we should point out in the docs.

> I don't see how a such large change in behaviour can be brought in seemingly under the radar.

And that's definitely not the goal - these recipe changes are tricky because they take effect immediately... hence why I wanted to write that blog post + these docs. Let's make those as foolproof as possible.

Thanks!

**Comment by bendavies** [comment]
@weaverryan you are right.

It's actually a nice edge case.
What our supervisor processors were running was, in effect:
`APP_ENV=prod bin/console whatever --env=prod`.

So they were specifying both, as we had moved the majority of config to env vars, but had not removed `--env=prod` from our supervisord config.

So on the old version, `.env` would not be loaded, on the new version, it is.

**Comment by weaverryan** [comment]
Oh interesting. I would also expect that the `.env` files would NOT be loaded in this situation, as you ARE specifying the `APP_ENV=prod` real environment var. Imo, the rule should be simple: if that `APP_ENV=prod` is set to a real env, no matter what else happens, the `.env` files should not be loaded. So, if this is the behavior you're getting, I think it's a bug.

**Comment by jlekowski** [comment]
@bendavies, I have the situation you describe. In my `Dockerfile`:
```
ENV APP_ENV "prod"
...
RUN bin/console cache:clear --no-warmup -vv --env=prod
```
And effectively in `bootstrap.php` my `$_SERVER['APP_ENV']` is `null` so it tries to use `DotEnv` which is `dev` dependency. It is very counter-intuitive that `--env=prod` makes environment non-prod at some point.

**Comment by weaverryan** [comment]
Thanks for the added info @jlekowski :).

When we were re-working the `.env` config loading, we thought a lot about the way it *should* work, and sometimes those are up to judgment. In this case, after talking with Nicolas, I think that this *should* be the behavior. It IS a change from before and I DO need to update the documentation to mention this. So basically:

> If you pass the `--env=` flag, this will override your APP_ENV environment variable (if set). And so, if you pass `--env=prod`, the `DotEnv` component *will* try to load your `.env*` files.

Updating your files to the new recipes is a behavior change, but the answer is simple: use `--env=prod` OR set your `APP_ENV` var, but not both. For these cases, you guys can just remove the `--env=prod`. I am sorry about the unexpected change (and I'm happy you reported it), but I think we should keep it.

Cheers!

**Comment by weaverryan** [comment]
Docs PR added!

**Comment by hackzilla** [comment]
@weaverryan I've just been caught out by this.
Yes this is a new app, but I've been using --env=prod for a long time.

```PHP Fatal error:  Uncaught RuntimeException: The "APP_ENV" environment variable is not set to "prod". Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.```

That sent me down the path of why isn't the variable sent.

`env` said it was.

What tripped me out was the unsetting of the variable.

```
    // force loading .env files when --env is defined
    $_SERVER['APP_ENV'] = null;
```

**Comment by weaverryan** [comment]
Ah, the error message is bad! In reality APP_ENV IS set in your situation, but it the `--env=prod` basically overrides this, and makes your `.env` files be loaded. We need a more intelligent error message to communicate this. In your situation, the fix is simple (but not clear): stop passing `--env=prod` - as you already have `APP_ENV` set properly.

**Comment by weaverryan** [comment]
Haha, yep - `APP_ENV=prod` as a real env variable is the only situation when your `.env` files are not loaded.

See #500
