### ISSUE TITLE
No default configuration for monolog provided

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/recipes#539]
There is currently no default configuration for monolog which will endup that if you add new environments to your application that nothing is logged. This ends up that you will not detect errors in the monitoring of a new environment.

**Comment by xabbuh** [comment]
I am not sure I understand what you mean. There is a [recipe for MonologBundle](https://github.com/symfony/recipes/tree/master/symfony/monolog-bundle/3.1).

**Comment by alexander-schranz** [comment]
@xabbuh sorry what I mean there is no default configuration `packages/monolog.yaml` which would be used for other environments. There is only a configuration for [`dev`, `test` and `prod`](https://github.com/symfony/recipes/tree/master/symfony/monolog-bundle/3.1/config/packages) and if you add a new environment it will have no logging by default, which I think should never be the behaviour.

**Comment by xabbuh** [comment]
If you add a new environment that does not extend one of the default environments, this is also true for all other installed packages, isn't it?

**Comment by alexander-schranz** [comment]
Most recipes provide a default configuration (doctrine, swiftmailer, framework, ...). And just see monolog as critical as I did seen that this was forgot mostly when creating a new environment and will really hide errors.

**Comment by Pierstoval** [comment]
Default monolog config for all envs is not a common thing, that's why Symfony provides different config for all 3 default envs, because these are different.

Some examples:
* In `dev`, we log everything.
* In `prod`, we send an email for errors and also send them to Sentry, and we log 404 errors in another file, as well as authentications, for debugging purposes.
* In `test`, we just log `info` and higher level messages because we run tests way more often than we use the dev env, and we don't want a 2GB file after running the test suite 5 times.

No default config could be acceptable as "base" for these three cases, therefore 3 different files is the best option.

And that's pretty much what the default recipe does (even though a bit less specific, but you get the idea).

**Comment by alexander-schranz** [comment]
@Pierstoval it would be easy possible to have a default logging in the recipe in your application (its symfony 😄  ) you can always change and in the environment overwrite it but it seems like you don't want to provide some.

Just want to say I did see this a common issue when someone creates a new environment that there was nothing logged and that this could be workaround by providing a default configuration for monolog for all envs.

Feel free to close it.

**Comment by Pierstoval** [comment]
As the handlers stack is looped through each time one logs something, I don't think spreading the configuration in multiple files is a good idea. In this case, which order will be used? First or second? Even if this is handled by Monolog, which I don't know, this is not "obvious" for anyone, contrary to specific files for each env.

**Comment by Tobion** [comment]
Can this be closed or someone wants to work on a PR?
