### ISSUE TITLE
Problem with orm-fixtures

### ISSUE THREAD

**Issue by ehibes** [symfony/recipes#700]
Hi,
I made an issue on https://github.com/doctrine/data-fixtures/issues/330. It seems to be a flex issue.

**Comment by xabbuh** [comment]
Symfony 4.1 is not maintained anymore. Please consider creating your new application with 4.4 or 5.0.

**Comment by stof** [comment]
I answered on the original issue. The issue here is that latest version of the DataFixturesBundle dropped support for EOLed Symfony versions, and the `composer require` command does not specify a constraint explicitly, which guesses a constraint requiring the latest available release.

There is no issue in the recipe (and no issue in the bundle either for that matter).
