### ISSUE TITLE
Trusted Proxy setting getting ip address instead of domain

### ISSUE THREAD

**Issue by naveen-23** [symfony/recipes#743]
Hi,

**File**: vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Request.php
**Method**: getHost() line 1152 

I used the below line to set trusted proxies in my application in file **public/index.php**
`Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);`

But it was returning IP address of reverse proxy server instead of domain name (HEADER_X_FORWARDED_HOST).

`Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST `
results to value of "**26**" 

which worked for HEADER_X_FORWARDED_FOR(value 2) which returned IP address , but not for 
HEADER_X_FORWARDED_HOST (value 4)

Solution to  make it work i change above line to this, 

In Receipe file : recipes/symfony/framework-bundle/4.4/public/index.php
`
Request::setTrustedProxies(explode(',', $trustedProxies),  Request::HEADER_X_FORWARDED_HOST);`

Is there any impact due to this?

**Comment by nicolas-grekas** [comment]
`Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST` means: trust all X-Forwarded headers except X-Forwarded-Host.

`Request::HEADER_X_FORWARDED_HOST` means: trust only X-Forwarded-Host

Anyway, this will be moved as semantic configuration in 5.2.

I'm closing since there is nothing related to recipes here. Maybe a doc issue could help explain this better?
