### ISSUE TITLE
Create recipes for popular web servers

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#78]
In the Symfony Standard Edition, we add .htaccess in some dirs to avoid unauthorized access. See https://github.com/symfony/symfony-standard/blob/3.3/src/.htaccess

Other people are asking us to add the equivalent of those files for IIS web server. See https://github.com/symfony/symfony/issues/22214

We could add recipes for "apache", "nginx" and "iis" to add these files and any other useful resource for those servers.

**Comment by teohhanhui** [comment]
I'd like to see Symfony Flex focus on configuring the Symfony "framework" and bundles. With what this issue proposes (and symfony/recipes-contrib#15 for example), we risk turning it into a tool that tries to do / manage everything.

**Comment by Pierstoval** [comment]
I'm not sure if I'm either for or against this proposal.

Either for apache or nginx, we are mostly talking about a default vhost configuration, which we can already find on symfony.com when looking for the right documentation. And for Apache, having an `.htaccess` file is not the best option because Apache reads this file on every request, and the config needs to be in the vhost for performance reasons.
And for nginx, the vhost would be copied to the server configuration anyway, could it be docker, heroku or whatever. And heroku has a different system for vhosts, as you cannot create "the full vhost", but only "a part of it" (mostly for nginx).

I think it would be a bit useless to `composer req nginx-conf` and still be forced to copy this config somewhere when deploying. Especially because server config often doesn't really change in time.

Contrary to @teohhanhui it's not because I want Flex to focus on framework & bundles (actually, it shouldn't, because Flex is made for **any** Composer package, not just bundles), but more because it would be a bit tricky to handle this need.

IMO, the documentation is enough for this.

**Comment by stof** [comment]
Actually, these `.htaccess` in symfony-standard are totally useless if you configure your vhost properly by making the `web` folder your document root (as `src` will not be accessible at all anymore).
so IMO, there is no need to focus on these unauthorized access. Instead, we should recommend people to configure their document root properly.

**Comment by fabpot** [comment]
Closing this issue as I don't think that it fits with Flex. We've seen in the past (mostly on Silex) that such configuration can differ widely depending on many other factors that are way out of the scope of Symfony.
