### ISSUE TITLE
[BC] [Symfony\Framework] AppKernel only loads yaml by default

### ISSUE THREAD

**Issue by silverbackdan** [symfony/recipes#783]
Regarding: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/src/Kernel.php

This recipe now by default only loads yaml configuration files. For those using xml, or in my case, php - this needs a manual update. Perhaps a user message/notice is needed for this?

Also, I don't know if this is the right place.. perhaps better in the flex repo as the feature may be needed there: It'd be good to be able to list conflicting files in the manifest so that, for example, if there is a `services.php` file present, the `services.yaml` is not added.

**Comment by stof** [comment]
Well, recipes are not re-applied automatically, precisely because the new version might not be BC with the old version.
The focus of recipes is to enable the "modern way" in projects starting to use a feature (which is why they will regularly opt-in for the new behaviors of Symfony, even though core bundles don't enable them by default for BC reasons). At the time you run `composer sync-recipes --force`, you need to be as careful as when you perform a major version bump.

**Comment by javiereguiluz** [comment]
@silverbackdan the idea behind recipes is that when doing `sync-recipes --force`, you need to carefully review each proposed change and decide what to keep and what to discard (the command output even shows the `git` instructions needed to do all this).

So, I think the only viable solution at this moment is to manually revert the changes you applied to the `Kernel` class and go back to loading not only YAML files. That's why I'm closing this issue but I hope you understand it. Thanks!

**Comment by silverbackdan** [comment]
Thank you both for your attention on this. I do understand all of the points here regarding the BC break so that's no issue at all.

There's no problem reverting for me, it's just a bit of a shame that by default the file used to dynamically include any type of configuration and now it's just the yaml. I wonder if this will need some extra explaining in the Symfony docs which give the option to show how to write configurations in xml and php as well. Perhaps this has been added as well and I haven't seen it.

Anyway, thanks again!
