### ISSUE TITLE
New symfony/psr-http-message-bridge recipe KO's out-of-the-box with sentry/symfony

### ISSUE THREAD

**Issue by weaverryan** [symfony/recipes#909]
Hi!

If you `composer require symfony/psr-http-message-bridge`, you get the new https://github.com/symfony/recipes/blob/master/symfony/psr-http-message-bridge/2.1/config/packages/psr_http_message_bridge.yaml config file.

This service config is, sort of, "invalid" when you first receive it. For example, if you actually tried to use the `PsrHttpFactory` service, you would get this error:

> Cannot autowire service "Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory":
> argument "$serverRequestFactory" of method "__construct()" references   
> interface "Psr\Http\Message\ServerRequestFactoryInterface" but no such service exists.
> Did you create a class that implements this interface?

The reason - which is included in the documentation - is that you also need to install an implementation - like `nyholm/psr7`.

That's not a great error messagae. But the *real* problem is when another package depends on `symfony/psr-http-message-bridge` - for example `sentry/sentry-symfony`. If you install it right now, it's currently broken (with the above error). This is what happens:

A) The symfony/psr-http-message-bridge recipe adds the (sort of) incomplete services file, which includes a non-functional `Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface` service, because it's an alias to the non-functional `Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory` service.

B) sentry/sentry-symfony uses `Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface` as an optional dependency - https://github.com/getsentry/sentry-symfony/blob/master/src/Resources/config/services.xml#L68

Everything works fine if there IS no `Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface` service. However, there now IS one... but it's broken, which gets you KO'ed on `composer install sentry/sentry-symfony`.

Sorry for the long explanation - it took me awhile to sort out the problem. 

**Possible Solution**

I would prefer if `symfony/psr-http-message-bridge` either came with no recipe (and the needed config is documented) or if it came with the config file, but commented-out. The user already needs to do more work to *actually* make the services functional.

I also don't use this library... so I don't know if its main use-case will be as a library that people directly install (and so we want to make that experience as smooth as possible) or if its an indirect dependency because people are installing things like sentry/sentry-symfony. In either case, adding the new services "broke the experience" of installing that library.

Thanks!

**Comment by nicolas-grekas** [comment]
> If they need a working PsrHttpFactory, they‘re better off wiring that service themselves.

that's the fix, right? no need for a bundle, since sentry-symfony should just do the extra miles it doesn't right now. Did I miss something? Anyone to send them a PR?

**Comment by weaverryan** [comment]
Thanks for the clarifications!

It's certainly atypical for a bundle to rely on a specific service id for injection - like they are here https://github.com/getsentry/sentry-symfony/blob/0e785459206d0d9c800d4998c807b7ef117d7439/src/Resources/config/services.xml#L68. 

But should that be considered wrong? If we instead (just as a thought experiment) had a PsrHttpMessageBridgeBundle that provided a `Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface`, would it be wrong then for them to rely on this (with the `on-invalid` behavior of course)? I think it wouldn't, as we do this all the time in bundles. So then, is what they're doing really wrong? I'm having a hard time making the case that THEY should fix something... especially since their bundle worked perfectly until this recipe was added.

Thanks!

**Comment by weaverryan** [comment]
> Yes, it's wrong to rely on a recipe - aka on userland services

Sorry, I think I haven't been clear.

`sentry/sentry-symfony` does NOT rely on this recipe :). It works perfectly fine (and worked perfectly fine) without it.

What they have is a service with an optional dependency on a service with id `Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface`: https://github.com/getsentry/sentry-symfony/blob/0e785459206d0d9c800d4998c807b7ef117d7439/src/Resources/config/services.xml#L66-L69

That's kind of nice: that service is not required (they create their own message factory if it isn't present). But if it IS present, then they use it. To me, this seems perfectly compatible with, for example, bundles relying on a `logger` service with `on-invalid` (before FrameworkBundle always provided it).

If it needs to be fixed on their end, the fix would be to add new config to their `Configuration` class to make the user explicitly  choose a custom message factory service - e.g. 


```yml
sentry:
    message_factory_service: 'Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'
```

That's definitely a valid solution... but should they really need to do that? We don't force people to opt into using the real `logger` service once MonologBundle is installed... bundles just start seeing it and using it.

Thanks!

**Comment by nicolas-grekas** [comment]
Got it. Then we might want to move the recipe from symfony/psr-http-message-bridge to symfony/psr7-pack, wdyt?

**Comment by derrabus** [comment]
> It's certainly atypical for a bundle to rely on a specific service id for injection

No, this is fine if that service is provided by the framework or a bundle. For instance, they could consume the `logger` service or the `serialzer` service and that would be absolutely okay because the framework makes sure that these services are present and properly configured.

Instead, they're consuming an autowire alias provided by userland code, assuming that this service is properly configured for their use case.

> But should that be considered wrong?

Yes! The whole system of service discovery + autowiring is built around the assumption that the container builder may contain incomplete service definitions. Consuming a userland autowire alias is asking for trouble.

> If we instead (just as a thought experiment) had a PsrHttpMessageBridgeBundle that provided a `Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface`, would it be wrong then for them to rely on this (with the `on-invalid` behavior of course)?

That bundle would probably provide something like a `psr_http_message.message_factory` service and it would only register that service if all the necessary requirements are met. And consuming that service would be okay for the reasons already mentioned.

So either way, if we had a bundle or not, they should not consume an autowire alias.

**Comment by Jean85** [comment]
Hi there, `sentry-symfony` maintainer here. I believe that Ryan perfectly described our position here (thank you!). We were using that service id to avoid creating a duplicated one, since the FWExtraBundle was providing it and so we could expect a large portion of our users have it already. As noticed, we don't fully rely on that and instantiate our own objects when missing.

I like @nicolas-grekas proposal to move the recipe to `symfony/psr7-pack`! :+1:

> Instead, they're consuming an autowire alias provided by userland code, assuming that this service is properly configured for their use case.

Nope, we were not relying on userland configuration, we were relying on a service exposed by the SensioFrameworkExtraBundle: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/430d14c01836b77c28092883d195a43ce413ee32/src/Resources/config/psr7.xml#L17

**Comment by nicolas-grekas** [comment]
> Instead, they're consuming an autowire alias provided by userland code, assuming that this service is properly configured for their use case.

Mmm, I'm mixed on this argument. I don't think it's really wrong. Creating an alias to a not-fully-defined service is more wrong to me... :) A pack would fix all this.

**Comment by weaverryan** [comment]
> A pack would fix all this.

👍  for a pack. It feels weird that we're currently shipping a non-fully-defined service in this recipe. A pack fixes both uses cases: (a) just needing `symfony/psr-http-message-bridge` as an indirect dependency like with sentry/sentry-symfony and (b) wanting to use this library to explicitly define some services (you would use the pack and get the recipe)

**Comment by derrabus** [comment]
I'd like to give the bundle idea a try: symfony/psr-http-message-bridge#94

**Comment by ste93cry** [comment]
>Instead, they're consuming an autowire alias provided by userland code, assuming that this service is properly configured for their use case

As said by others, what `getsentry/sentry-symfony` is doing is the exact same thing as relying on the `LoggerInterface` service which is an alias to the `logger` service. What is atypical for me is that a recipe (or bundle, not important) registers an alias to a service that is `null` (literally). I've never encountered this situation before and looks completely wrong because it will break anything that is using the `on-invalid="null"` option of the DI container

**Comment by derrabus** [comment]
Please have a look at the bundle I've created. It registers the services of all requirements are met. This should eliminate the situation where an incomplete `PsrHttpFactory` definition is registered in the container. You can find the updated recipe in #910.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/recipes/issues/909 for the "psr7-pack" approach.
