### ISSUE TITLE
[doctrine/doctrine-bundle] Is serverVersion really still required?

### ISSUE THREAD

**Issue by GPHemsley-RELX** [symfony/recipes#946]
The recipe for doctrine/doctrine-bundle has carried through a message that server_version or serverVersion *must* be set for the DATABASE_URL without much discussion for a long time now. However, [the Doctrine DBAL documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.12/reference/configuration.html#automatic-platform-version-detection) indicates that the server version has been reliably detected at runtime since DBAL 2.5.

According to git history, doctrine/doctrine-bundle has required DBAL 2.5+ since version 1.7.0:
https://github.com/doctrine/DoctrineBundle/commit/88d67f147deb4c3f67aa09484e6deaf66d2ddf03

Does Symfony have a requirement that serverVersion be set above and beyond that required by Doctrine DBAL? If so, can that requirement be added to the configuration comment to make it clear? Otherwise, can the comment be removed?

**Comment by GPHemsley-RELX** [comment]
> Yes: the setting is required in order to compile the container offline.

Can you be more specific about this usecase? We stopped specifying server version and our app has not displayed any obvious issues.

**Comment by stof** [comment]
the ORM metadata depend on the database platform (due to smart defaults and stuff like that). So things that affect the selection of the platform (the driver and the server version) must be known at cache warmup time.
We already got bug reports in the past few weeks about weird errors happening when a project is warmed up with a different selection of the platform (the generated cache won't be automatically invalidated by the ORM, so it might do wrong things)
